### PR TITLE
Make Quinoa work

### PR DESCRIPTION
**Pull request by ia3andy**
The problem is with ESLINT, in the CI, `CI=true` makes react-scripts do the eslint check in error mode. 
In the maven-frontend-plugin config you had `CI=false` but this is wrong since it's not really the fix.

I fixed the problem using `DISABLE_ESLINT_PLUGIN`, let's see if the CI passes now..

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by ia3andy** [comment]
Also @valdar you should consider actually fixing what eslint is complaining about (or editing the rules)

**Comment by oscerd** [comment]
@mgubaidullin this is for you.

**Comment by ia3andy** [comment]
Something else I wasn't able to run locally because you need to have some envs `GIT_REPOSITORY `, ... could you add the way to configure it for local dev in the dev doc https://github.com/apache/camel-karavan/blob/main/DEV.md

**Comment by ia3andy** [comment]
@oscerd @mgubaidullin we can't make sure currently it works as the CI is disabled if it's not main. I will test on my fork, please do not merge yet

**Comment by mgubaidullin** [comment]
> Something else I wasn't able to run locally because you need to have some envs `GIT_REPOSITORY `, ... could you add the way to configure it for local dev in the dev doc https://github.com/apache/camel-karavan/blob/main/DEV.md

1. Check. Local run works fine 
2. https://github.com/apache/camel-karavan/issues/630

**Comment by ia3andy** [comment]
I am testing on my local branch, for now it fails, but I am close to have it working..

**Comment by ia3andy** [comment]
@mgubaidullin the Quinoa build part is passing on my fork, there is an error when pushing the image afteward but I guess it won't happen on this repo. So it's good to be merged

**Comment by ia3andy** [comment]
I've tried to use `npm ci` (frozen-lockfile) in the quinoa build but for some reason it's not happy with the local dependency so I disabled it (which was already the case anyway since CI was set to false).

**Comment by mgubaidullin** [comment]
Thank you @ia3andy. Welcome to Karavan contributors!

**Comment by mgubaidullin** [comment]
I will ping you when we need `npm ci` work ;-)

**Pull request merged**
