### PR TITLE
bug fix when expression is not string

### PR DESCRIPTION
**Pull request by httpsOmkar**
fixed the bug when we use the following yaml

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: SOME_INTEGRATION
spec:
  flows:
    - from:
        parameters:
          subpath: SOME_PATH
        uri: 'kamelet:webhook-source'
        steps:
          - filter:
              expression:
                jsonpath:
                  expression: $.some.data.that.doesnt.exists
                  suppress-exceptions: true
              steps:
                - remove-headers:
                    pattern: '*'
```

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I don't think it must be removed

**Comment by httpsOmkar** [comment]
> I don't think it must be removed

what should I remove?

**Comment by oscerd** [comment]
You shouldn't remove package-lock.json and yarn.lock

**Comment by httpsOmkar** [comment]
I just removed the package-lock.json since the integrity of the packages is tracked in `yarn.lock` I assumed that the project is using a yarn by default. Since the other folder which is `karavan-designer` have only yarn.lock

**Comment by httpsOmkar** [comment]
It's not good practice to use different package managers. Let me know if we use only npm instead of yarn. I'll remove the yarn.lock instead

**Comment by oscerd** [comment]
Yes, but it's not related to the fix in the .tsx file. I think if it must be done, it should be in different commit. By the way wait for @mgubaidullin

**Comment by httpsOmkar** [comment]
Yeah, you are right. I'll address into different MR for the package-lock.json.

**Comment by httpsOmkar** [comment]
I restored the package-lock.json

**Comment by mgubaidullin** [comment]
Currently Karavan supports only implicit and explicit Expression definition. Ex. yaml for your case:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: jsonpath-test.yaml
spec:
  flows:
    - from:
        uri: 'kamelet:webhook-source'
        steps:
          - filter:
              expression:
                jsonpath: $.some.data.that.doesnt.exists
          - remove-headers:
              pattern: '*'
        parameters:
          subpath: SOME_PATH
```

UI
Screen Shot 2021-11-25 at 7 45 49 AM


Full Expression definition is not yet implemented.

**Comment by httpsOmkar** [comment]
can I implement it?

**Comment by mgubaidullin** [comment]
@httpsOmkar yes, contributions are welcome. This one is quite complex (that's why it is not yet implemented 😉

However, to make it work you'll need to create 
1. Generator from `camel-yaml-dsl.json` to CamelModel, CamelAPI, CamelMetadata for all 21 expression languages
2. Implement UI builder new Models in DslProperties
3. Adjust CamelYaml to read/write all types (implicit/explicit/full expressions) correctly

**Pull request closed without merging**
