### PR TITLE
Added support to Download Integration as an image

### PR DESCRIPTION
**Pull request by mrinalsharma**

### CODE REVIEW

**Comment by mgubaidullin** [comment]
@mrinalsharma Thanks! Great job.

Could you please check. In VS Code Dark Mode I have image without text.
karavan-routes

**Comment by mgubaidullin** [comment]
I moved `Download Image` button from main Designer view to Application and VSCode panel
https://github.com/apache/camel-karavan/commit/87e5bccc5a3871722c7dab1fa35587589686b258

Could you please put 'Download Image' functionality into downloadImage() function in KaravanDesigner.

**Comment by mrinalsharma** [comment]
I just noticed the VisualCode Dark mode issue. If I re-download it then it prints fine.

**Comment by mgubaidullin** [comment]
You could to a re-try like this as a temporary workaround to make it work:
```
toPng(this.state.printerRef.current).then(v => {
    toPng(this.state.printerRef.current, { style:{overflow:'hidden'}, cacheBust: true, filter: this.IntegrationDownloadFilter, 
        height:this.state.height,width:this.state.width,  backgroundColor: this.props.dark?"black":"white" }).then(this.downloadIntegrationImage);
    });
```
And then investigate the why it does not do it correct for the first time.

**Comment by mgubaidullin** [comment]
@mrinalsharma could you please rebase instead of merge to keep clean commits

**Comment by mrinalsharma** [comment]
> @mrinalsharma could you please rebase instead of merge to keep clean commits

Sure.

**Comment by mrinalsharma** [comment]
> I moved `Download Image` button from main Designer view to Application and VSCode panel [87e5bcc](https://github.com/apache/camel-karavan/commit/87e5bccc5a3871722c7dab1fa35587589686b258)
> 
> Could you please put 'Download Image' functionality into downloadImage() function in KaravanDesigner.

Why do you think this download code should be in KaravanDesigner. We want to print an image of route and the RouteDesigner has all the details needed to print. If we make a change in KaravanDesigner then from RouteDesigner we need to notify KaravanDesigner about height and width of the RouteDesigner area that needs to be printed. We would also have to filter out extra "classes" from a printable node that are not part ofRouteDesigner.

**Comment by mgubaidullin** [comment]
Agree download code itself should be in RouteDesigner.

However the `Download Image` button should not be there, because it is not a part of designing, 
but control button as others `Download code`, `Run` etc  and should in `Tools` panel and `Editor` panel respectively.

**Comment by mgubaidullin** [comment]
Thanks @mrinalsharma 
Well done!

**Pull request merged**
