### PR TITLE
Refactoring of Karavan Core

### PR DESCRIPTION
**Pull request by f-ambroz**
- Bumped up the version of typescript to ES2022
- Added prettier to the project
- Refactored iterating so it uses classic _**for**_ loops for better performance
- Added private constructors to static classes

### CODE REVIEW

**Comment by mgubaidullin** [comment]
@f-ambroz thanks!
Could you please fix tests in karavan-core (just simple sort yaml results) and vscode build ?

**Comment by f-ambroz** [comment]
> @f-ambroz thanks! Could you please fix tests in karavan-core (just simple sort yaml results) and vscode build ?

Will do!

**Comment by f-ambroz** [comment]
@mgubaidullin Tests are fixed. So the build should work now.

**Comment by f-ambroz** [comment]
@mgubaidullin everything seems to be fixed :)

**Comment by mgubaidullin** [comment]
@f-ambroz is it OK that karavan-app is still `"target": "es5"` while core, designer are `"target": "es2022"` ?

**Comment by f-ambroz** [comment]
> @f-ambroz is it OK that karavan-app is still `"target": "es5"` while core, designer are `"target": "es2022"` ?

That is a good question that I do not have the answer for. 😄
Theoretically, it should be OK, but this is javascript we are talking about, so I am not sure.

**Pull request merged**
