### PR TITLE
Fix numeric field bug: Backspace not removing last value

### PR DESCRIPTION
**Pull request by Praval791**
Resolved an issue where the backspace key was not functioning correctly in the numeric input field, preventing users from clearing the field.

### Changes Made

- Ensured that the numeric field can be cleared entirely when the backspace key is pressed.

### Steps to Reproduce

1. Create a route 
2. add a kamelet that have the numeric input field. 
3. Enter a numeric value into the field.
4. Attempt to clear the field using the backspace key.

### Expected Behavior

The numeric field should be completely cleared when the backspace key is pressed repeatedly.

### Actual Behavior

The last value remains in the field, and the field cannot be emptied using the backspace key.

#### demo video

https://github.com/apache/camel-karavan/assets/94207665/cf9c36eb-0970-492c-893b-232d0e0d7905

### CODE REVIEW

**Comment by mgubaidullin** [comment]
@Praval791 thank you for your contribution.

**Comment by mgubaidullin** [comment]
@Praval791, next time, please, avoid mass format like [this one](https://github.com/apache/camel-karavan/pull/1314/files#diff-95c47dc03894f269c63040270f5a17238063488a49a5e0d2d62bbec4a553ebeb)

Thank again for your contribution

**Comment by mgubaidullin** [comment]
@Praval791 unfortunately I need to rollback your PR.

Numeric fields in DSL, Kamelets and Components may have explicit Numeric value or a placeholder, ex: `{{env:ENV_NAME}}`, `{{property}}`

**Comment by Praval791** [comment]
> @Praval791 unfortunately I need to rollback your PR.
> 
> Numeric fields in DSL, Kamelets and Components may have explicit Numeric value or a placeholder, ex: `{{env:ENV_NAME}}`, `{{property}}`

Hi @mgubaidullin 
Thank you for the feedback. I understand that the numeric fields can also contain placeholders (If I got you correctly) and that my initial fix may not have accounted for this properly.

To clarify the issue with a specific example, consider the following YAML configuration:

```yaml
- route:
    id: route-d9b6
    nodePrefixId: route-7cc
    from:
      id: from-03ee
      uri: kamelet:aws-cloudtrail-source
      parameters:
        maxResults: 2
      steps:
        - to:
            id: to-ec0e
            uri: activemq
            parameters:
              deliveryDelay: "1213"
```

In this configuration, if you try to remove the maxResults field, you will notice that the backspace key does not allow clearing the value completely but the same thing is working in components. I only got this issue in Kamelets and DSL. 

I will work on modifying my fix to ensure that both numeric values and placeholders are handled correctly. To help me better understand the requirements and make the necessary changes, could you please provide an example YAML configuration that includes placeholders? This would greatly assist me in ensuring that my fix covers all use cases.

Thank you for your understanding and assistance.

**Comment by mgubaidullin** [comment]
I have jus copy-pasted code from Component to Kamelets and DSL to support placeholders https://github.com/apache/camel-karavan/commit/25449b1fc4577e012882a176d44f638089456e85

**Pull request merged**
