### PR TITLE
mvolf - web - Implement copy project functionality

### PR DESCRIPTION
**Pull request by mvolf**
Copy project functionality for web application

### CODE REVIEW

**Comment by mgubaidullin** [comment]
Copy project should be implemented in backend.
1. Create project `new_project`
2. Copy files from `old_project` to `new_project`
3. While copying:
- Change project name and gav properties in `application.properties`
- If project in Docker then set `projectPort` in docker-compose.yaml. Find next available port same way as when creating new project.

**Comment by mvolf** [comment]
@mgubaidullin Thanks for the feedback. I'll add the implementation for the necessary file modifications when I catch some time and update the PR.

**Comment by mvolf** [comment]
@mgubaidullin I propose not copying docker-compose.yaml from the parent project, but rather creating a new one, since we don't need to migrate any of the values from the parent file (as far as I'm aware).
Do you see any drawbacks with this?

**Comment by mvolf** [comment]
I'll create a new PR with new implementation once done.

**Pull request closed without merging**
